//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentAppClient.RecAppServiceRef {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://applications/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://applications/")]
    public partial class jobOffer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contact_emailField;
        
        private string contact_phoneField;
        
        private string contract_typeField;
        
        private string descriptionField;
        
        private double max_salaryField;
        
        private bool max_salaryFieldSpecified;
        
        private double min_salaryField;
        
        private bool min_salaryFieldSpecified;
        
        private string titleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contact_email {
            get {
                return this.contact_emailField;
            }
            set {
                this.contact_emailField = value;
                this.RaisePropertyChanged("contact_email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string contact_phone {
            get {
                return this.contact_phoneField;
            }
            set {
                this.contact_phoneField = value;
                this.RaisePropertyChanged("contact_phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string contract_type {
            get {
                return this.contract_typeField;
            }
            set {
                this.contract_typeField = value;
                this.RaisePropertyChanged("contract_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double max_salary {
            get {
                return this.max_salaryField;
            }
            set {
                this.max_salaryField = value;
                this.RaisePropertyChanged("max_salary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool max_salarySpecified {
            get {
                return this.max_salaryFieldSpecified;
            }
            set {
                this.max_salaryFieldSpecified = value;
                this.RaisePropertyChanged("max_salarySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double min_salary {
            get {
                return this.min_salaryField;
            }
            set {
                this.min_salaryField = value;
                this.RaisePropertyChanged("min_salary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool min_salarySpecified {
            get {
                return this.min_salaryFieldSpecified;
            }
            set {
                this.min_salaryFieldSpecified = value;
                this.RaisePropertyChanged("min_salarySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://applications/")]
    public partial class applicant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string nameField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://applications/")]
    public partial class application : object, System.ComponentModel.INotifyPropertyChanged {
        
        private applicant applicantField;
        
        private bool data_processing_agreementField;
        
        private bool data_processing_agreementFieldSpecified;
        
        private string dateField;
        
        private jobOffer jobOfferField;
        
        private string notesField;
        
        private string recruiterField;
        
        private string statusField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public applicant applicant {
            get {
                return this.applicantField;
            }
            set {
                this.applicantField = value;
                this.RaisePropertyChanged("applicant");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool data_processing_agreement {
            get {
                return this.data_processing_agreementField;
            }
            set {
                this.data_processing_agreementField = value;
                this.RaisePropertyChanged("data_processing_agreement");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool data_processing_agreementSpecified {
            get {
                return this.data_processing_agreementFieldSpecified;
            }
            set {
                this.data_processing_agreementFieldSpecified = value;
                this.RaisePropertyChanged("data_processing_agreementSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public jobOffer jobOffer {
            get {
                return this.jobOfferField;
            }
            set {
                this.jobOfferField = value;
                this.RaisePropertyChanged("jobOffer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string recruiter {
            get {
                return this.recruiterField;
            }
            set {
                this.recruiterField = value;
                this.RaisePropertyChanged("recruiter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://applications/", ConfigurationName="RecAppServiceRef.ApplicationsManager")]
    public interface ApplicationsManager {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/getApplicationsRequest", ReplyAction="http://applications/ApplicationsManager/getApplicationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RecruitmentAppClient.RecAppServiceRef.getApplicationsResponse getApplications(RecruitmentAppClient.RecAppServiceRef.getApplicationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/getApplicationsRequest", ReplyAction="http://applications/ApplicationsManager/getApplicationsResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.getApplicationsResponse> getApplicationsAsync(RecruitmentAppClient.RecAppServiceRef.getApplicationsRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/setApplicationsRequest", ReplyAction="http://applications/ApplicationsManager/setApplicationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RecruitmentAppClient.RecAppServiceRef.setApplicationsResponse setApplications(RecruitmentAppClient.RecAppServiceRef.setApplicationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/setApplicationsRequest", ReplyAction="http://applications/ApplicationsManager/setApplicationsResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.setApplicationsResponse> setApplicationsAsync(RecruitmentAppClient.RecAppServiceRef.setApplicationsRequest request);
        
        // CODEGEN: Parameter 'application' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/searchByApplicantRequest", ReplyAction="http://applications/ApplicationsManager/searchByApplicantResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="application")]
        RecruitmentAppClient.RecAppServiceRef.searchByApplicantResponse searchByApplicant(RecruitmentAppClient.RecAppServiceRef.searchByApplicantRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/searchByApplicantRequest", ReplyAction="http://applications/ApplicationsManager/searchByApplicantResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByApplicantResponse> searchByApplicantAsync(RecruitmentAppClient.RecAppServiceRef.searchByApplicantRequest request);
        
        // CODEGEN: Parameter 'application' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/searchByRecruiterRequest", ReplyAction="http://applications/ApplicationsManager/searchByRecruiterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="application")]
        RecruitmentAppClient.RecAppServiceRef.searchByRecruiterResponse searchByRecruiter(RecruitmentAppClient.RecAppServiceRef.searchByRecruiterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/searchByRecruiterRequest", ReplyAction="http://applications/ApplicationsManager/searchByRecruiterResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByRecruiterResponse> searchByRecruiterAsync(RecruitmentAppClient.RecAppServiceRef.searchByRecruiterRequest request);
        
        // CODEGEN: Parameter 'removed' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/removeApplicationRequest", ReplyAction="http://applications/ApplicationsManager/removeApplicationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecruitmentAppClient.RecAppServiceRef.Exception), Action="http://applications/ApplicationsManager/removeApplication/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="removed")]
        RecruitmentAppClient.RecAppServiceRef.removeApplicationResponse removeApplication(RecruitmentAppClient.RecAppServiceRef.removeApplicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/removeApplicationRequest", ReplyAction="http://applications/ApplicationsManager/removeApplicationResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.removeApplicationResponse> removeApplicationAsync(RecruitmentAppClient.RecAppServiceRef.removeApplicationRequest request);
        
        // CODEGEN: Parameter 'application' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/searchByOfferRequest", ReplyAction="http://applications/ApplicationsManager/searchByOfferResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="application")]
        RecruitmentAppClient.RecAppServiceRef.searchByOfferResponse searchByOffer(RecruitmentAppClient.RecAppServiceRef.searchByOfferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/searchByOfferRequest", ReplyAction="http://applications/ApplicationsManager/searchByOfferResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByOfferResponse> searchByOfferAsync(RecruitmentAppClient.RecAppServiceRef.searchByOfferRequest request);
        
        // CODEGEN: Parameter 'sessionID' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/loginRequest", ReplyAction="http://applications/ApplicationsManager/loginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecruitmentAppClient.RecAppServiceRef.Exception), Action="http://applications/ApplicationsManager/login/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="sessionID")]
        RecruitmentAppClient.RecAppServiceRef.loginResponse login(RecruitmentAppClient.RecAppServiceRef.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/loginRequest", ReplyAction="http://applications/ApplicationsManager/loginResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.loginResponse> loginAsync(RecruitmentAppClient.RecAppServiceRef.loginRequest request);
        
        // CODEGEN: Parameter 'result' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/logoutRequest", ReplyAction="http://applications/ApplicationsManager/logoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecruitmentAppClient.RecAppServiceRef.Exception), Action="http://applications/ApplicationsManager/logout/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        RecruitmentAppClient.RecAppServiceRef.logoutResponse logout(RecruitmentAppClient.RecAppServiceRef.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/logoutRequest", ReplyAction="http://applications/ApplicationsManager/logoutResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.logoutResponse> logoutAsync(RecruitmentAppClient.RecAppServiceRef.logoutRequest request);
        
        // CODEGEN: Parameter 'application' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/searchByStatusRequest", ReplyAction="http://applications/ApplicationsManager/searchByStatusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="application")]
        RecruitmentAppClient.RecAppServiceRef.searchByStatusResponse searchByStatus(RecruitmentAppClient.RecAppServiceRef.searchByStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/searchByStatusRequest", ReplyAction="http://applications/ApplicationsManager/searchByStatusResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByStatusResponse> searchByStatusAsync(RecruitmentAppClient.RecAppServiceRef.searchByStatusRequest request);
        
        // CODEGEN: Parameter 'added' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/addApplicationRequest", ReplyAction="http://applications/ApplicationsManager/addApplicationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RecruitmentAppClient.RecAppServiceRef.Exception), Action="http://applications/ApplicationsManager/addApplication/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="added")]
        RecruitmentAppClient.RecAppServiceRef.addApplicationResponse addApplication(RecruitmentAppClient.RecAppServiceRef.addApplicationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://applications/ApplicationsManager/addApplicationRequest", ReplyAction="http://applications/ApplicationsManager/addApplicationResponse")]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.addApplicationResponse> addApplicationAsync(RecruitmentAppClient.RecAppServiceRef.addApplicationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getApplications", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class getApplicationsRequest {
        
        public getApplicationsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getApplicationsResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class getApplicationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecruitmentAppClient.RecAppServiceRef.application[] @return;
        
        public getApplicationsResponse() {
        }
        
        public getApplicationsResponse(RecruitmentAppClient.RecAppServiceRef.application[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setApplications", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class setApplicationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecruitmentAppClient.RecAppServiceRef.application[] arg0;
        
        public setApplicationsRequest() {
        }
        
        public setApplicationsRequest(RecruitmentAppClient.RecAppServiceRef.application[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setApplicationsResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class setApplicationsResponse {
        
        public setApplicationsResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByApplicant", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class searchByApplicantRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string applicant;
        
        public searchByApplicantRequest() {
        }
        
        public searchByApplicantRequest(string applicant) {
            this.applicant = applicant;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByApplicantResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class searchByApplicantResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("application", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecruitmentAppClient.RecAppServiceRef.application[] application;
        
        public searchByApplicantResponse() {
        }
        
        public searchByApplicantResponse(RecruitmentAppClient.RecAppServiceRef.application[] application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByRecruiter", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class searchByRecruiterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recruiter;
        
        public searchByRecruiterRequest() {
        }
        
        public searchByRecruiterRequest(string recruiter) {
            this.recruiter = recruiter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByRecruiterResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class searchByRecruiterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("application", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecruitmentAppClient.RecAppServiceRef.application[] application;
        
        public searchByRecruiterResponse() {
        }
        
        public searchByRecruiterResponse(RecruitmentAppClient.RecAppServiceRef.application[] application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeApplication", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class removeApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public removeApplicationRequest() {
        }
        
        public removeApplicationRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeApplicationResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class removeApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool removed;
        
        public removeApplicationResponse() {
        }
        
        public removeApplicationResponse(bool removed) {
            this.removed = removed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByOffer", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class searchByOfferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string offer;
        
        public searchByOfferRequest() {
        }
        
        public searchByOfferRequest(string offer) {
            this.offer = offer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByOfferResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class searchByOfferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("application", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecruitmentAppClient.RecAppServiceRef.application[] application;
        
        public searchByOfferResponse() {
        }
        
        public searchByOfferResponse(RecruitmentAppClient.RecAppServiceRef.application[] application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public loginRequest() {
        }
        
        public loginRequest(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionID;
        
        public loginResponse() {
        }
        
        public loginResponse(string sessionID) {
            this.sessionID = sessionID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logout", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sessionid;
        
        public logoutRequest() {
        }
        
        public logoutRequest(string sessionid) {
            this.sessionid = sessionid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logoutResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public logoutResponse() {
        }
        
        public logoutResponse(bool result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByStatus", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class searchByStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string status;
        
        public searchByStatusRequest() {
        }
        
        public searchByStatusRequest(string status) {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchByStatusResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class searchByStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("application", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecruitmentAppClient.RecAppServiceRef.application[] application;
        
        public searchByStatusResponse() {
        }
        
        public searchByStatusResponse(RecruitmentAppClient.RecAppServiceRef.application[] application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addApplication", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class addApplicationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RecruitmentAppClient.RecAppServiceRef.application application;
        
        public addApplicationRequest() {
        }
        
        public addApplicationRequest(RecruitmentAppClient.RecAppServiceRef.application application) {
            this.application = application;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addApplicationResponse", WrapperNamespace="http://applications/", IsWrapped=true)]
    public partial class addApplicationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://applications/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool added;
        
        public addApplicationResponse() {
        }
        
        public addApplicationResponse(bool added) {
            this.added = added;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApplicationsManagerChannel : RecruitmentAppClient.RecAppServiceRef.ApplicationsManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationsManagerClient : System.ServiceModel.ClientBase<RecruitmentAppClient.RecAppServiceRef.ApplicationsManager>, RecruitmentAppClient.RecAppServiceRef.ApplicationsManager {
        
        public ApplicationsManagerClient() {
        }
        
        public ApplicationsManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationsManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationsManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationsManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.getApplicationsResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.getApplications(RecruitmentAppClient.RecAppServiceRef.getApplicationsRequest request) {
            return base.Channel.getApplications(request);
        }
        
        public RecruitmentAppClient.RecAppServiceRef.application[] getApplications() {
            RecruitmentAppClient.RecAppServiceRef.getApplicationsRequest inValue = new RecruitmentAppClient.RecAppServiceRef.getApplicationsRequest();
            RecruitmentAppClient.RecAppServiceRef.getApplicationsResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).getApplications(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.getApplicationsResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.getApplicationsAsync(RecruitmentAppClient.RecAppServiceRef.getApplicationsRequest request) {
            return base.Channel.getApplicationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.getApplicationsResponse> getApplicationsAsync() {
            RecruitmentAppClient.RecAppServiceRef.getApplicationsRequest inValue = new RecruitmentAppClient.RecAppServiceRef.getApplicationsRequest();
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).getApplicationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.setApplicationsResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.setApplications(RecruitmentAppClient.RecAppServiceRef.setApplicationsRequest request) {
            return base.Channel.setApplications(request);
        }
        
        public void setApplications(RecruitmentAppClient.RecAppServiceRef.application[] arg0) {
            RecruitmentAppClient.RecAppServiceRef.setApplicationsRequest inValue = new RecruitmentAppClient.RecAppServiceRef.setApplicationsRequest();
            inValue.arg0 = arg0;
            RecruitmentAppClient.RecAppServiceRef.setApplicationsResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).setApplications(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.setApplicationsResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.setApplicationsAsync(RecruitmentAppClient.RecAppServiceRef.setApplicationsRequest request) {
            return base.Channel.setApplicationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.setApplicationsResponse> setApplicationsAsync(RecruitmentAppClient.RecAppServiceRef.application[] arg0) {
            RecruitmentAppClient.RecAppServiceRef.setApplicationsRequest inValue = new RecruitmentAppClient.RecAppServiceRef.setApplicationsRequest();
            inValue.arg0 = arg0;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).setApplicationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.searchByApplicantResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.searchByApplicant(RecruitmentAppClient.RecAppServiceRef.searchByApplicantRequest request) {
            return base.Channel.searchByApplicant(request);
        }
        
        public RecruitmentAppClient.RecAppServiceRef.application[] searchByApplicant(string applicant) {
            RecruitmentAppClient.RecAppServiceRef.searchByApplicantRequest inValue = new RecruitmentAppClient.RecAppServiceRef.searchByApplicantRequest();
            inValue.applicant = applicant;
            RecruitmentAppClient.RecAppServiceRef.searchByApplicantResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).searchByApplicant(inValue);
            return retVal.application;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByApplicantResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.searchByApplicantAsync(RecruitmentAppClient.RecAppServiceRef.searchByApplicantRequest request) {
            return base.Channel.searchByApplicantAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByApplicantResponse> searchByApplicantAsync(string applicant) {
            RecruitmentAppClient.RecAppServiceRef.searchByApplicantRequest inValue = new RecruitmentAppClient.RecAppServiceRef.searchByApplicantRequest();
            inValue.applicant = applicant;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).searchByApplicantAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.searchByRecruiterResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.searchByRecruiter(RecruitmentAppClient.RecAppServiceRef.searchByRecruiterRequest request) {
            return base.Channel.searchByRecruiter(request);
        }
        
        public RecruitmentAppClient.RecAppServiceRef.application[] searchByRecruiter(string recruiter) {
            RecruitmentAppClient.RecAppServiceRef.searchByRecruiterRequest inValue = new RecruitmentAppClient.RecAppServiceRef.searchByRecruiterRequest();
            inValue.recruiter = recruiter;
            RecruitmentAppClient.RecAppServiceRef.searchByRecruiterResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).searchByRecruiter(inValue);
            return retVal.application;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByRecruiterResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.searchByRecruiterAsync(RecruitmentAppClient.RecAppServiceRef.searchByRecruiterRequest request) {
            return base.Channel.searchByRecruiterAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByRecruiterResponse> searchByRecruiterAsync(string recruiter) {
            RecruitmentAppClient.RecAppServiceRef.searchByRecruiterRequest inValue = new RecruitmentAppClient.RecAppServiceRef.searchByRecruiterRequest();
            inValue.recruiter = recruiter;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).searchByRecruiterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.removeApplicationResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.removeApplication(RecruitmentAppClient.RecAppServiceRef.removeApplicationRequest request) {
            return base.Channel.removeApplication(request);
        }
        
        public bool removeApplication(string id) {
            RecruitmentAppClient.RecAppServiceRef.removeApplicationRequest inValue = new RecruitmentAppClient.RecAppServiceRef.removeApplicationRequest();
            inValue.id = id;
            RecruitmentAppClient.RecAppServiceRef.removeApplicationResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).removeApplication(inValue);
            return retVal.removed;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.removeApplicationResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.removeApplicationAsync(RecruitmentAppClient.RecAppServiceRef.removeApplicationRequest request) {
            return base.Channel.removeApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.removeApplicationResponse> removeApplicationAsync(string id) {
            RecruitmentAppClient.RecAppServiceRef.removeApplicationRequest inValue = new RecruitmentAppClient.RecAppServiceRef.removeApplicationRequest();
            inValue.id = id;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).removeApplicationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.searchByOfferResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.searchByOffer(RecruitmentAppClient.RecAppServiceRef.searchByOfferRequest request) {
            return base.Channel.searchByOffer(request);
        }
        
        public RecruitmentAppClient.RecAppServiceRef.application[] searchByOffer(string offer) {
            RecruitmentAppClient.RecAppServiceRef.searchByOfferRequest inValue = new RecruitmentAppClient.RecAppServiceRef.searchByOfferRequest();
            inValue.offer = offer;
            RecruitmentAppClient.RecAppServiceRef.searchByOfferResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).searchByOffer(inValue);
            return retVal.application;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByOfferResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.searchByOfferAsync(RecruitmentAppClient.RecAppServiceRef.searchByOfferRequest request) {
            return base.Channel.searchByOfferAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByOfferResponse> searchByOfferAsync(string offer) {
            RecruitmentAppClient.RecAppServiceRef.searchByOfferRequest inValue = new RecruitmentAppClient.RecAppServiceRef.searchByOfferRequest();
            inValue.offer = offer;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).searchByOfferAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.loginResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.login(RecruitmentAppClient.RecAppServiceRef.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string login1, string password) {
            RecruitmentAppClient.RecAppServiceRef.loginRequest inValue = new RecruitmentAppClient.RecAppServiceRef.loginRequest();
            inValue.login = login1;
            inValue.password = password;
            RecruitmentAppClient.RecAppServiceRef.loginResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).login(inValue);
            return retVal.sessionID;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.loginResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.loginAsync(RecruitmentAppClient.RecAppServiceRef.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.loginResponse> loginAsync(string login, string password) {
            RecruitmentAppClient.RecAppServiceRef.loginRequest inValue = new RecruitmentAppClient.RecAppServiceRef.loginRequest();
            inValue.login = login;
            inValue.password = password;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.logoutResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.logout(RecruitmentAppClient.RecAppServiceRef.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public bool logout(string sessionid) {
            RecruitmentAppClient.RecAppServiceRef.logoutRequest inValue = new RecruitmentAppClient.RecAppServiceRef.logoutRequest();
            inValue.sessionid = sessionid;
            RecruitmentAppClient.RecAppServiceRef.logoutResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).logout(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.logoutResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.logoutAsync(RecruitmentAppClient.RecAppServiceRef.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.logoutResponse> logoutAsync(string sessionid) {
            RecruitmentAppClient.RecAppServiceRef.logoutRequest inValue = new RecruitmentAppClient.RecAppServiceRef.logoutRequest();
            inValue.sessionid = sessionid;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.searchByStatusResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.searchByStatus(RecruitmentAppClient.RecAppServiceRef.searchByStatusRequest request) {
            return base.Channel.searchByStatus(request);
        }
        
        public RecruitmentAppClient.RecAppServiceRef.application[] searchByStatus(string status) {
            RecruitmentAppClient.RecAppServiceRef.searchByStatusRequest inValue = new RecruitmentAppClient.RecAppServiceRef.searchByStatusRequest();
            inValue.status = status;
            RecruitmentAppClient.RecAppServiceRef.searchByStatusResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).searchByStatus(inValue);
            return retVal.application;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByStatusResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.searchByStatusAsync(RecruitmentAppClient.RecAppServiceRef.searchByStatusRequest request) {
            return base.Channel.searchByStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.searchByStatusResponse> searchByStatusAsync(string status) {
            RecruitmentAppClient.RecAppServiceRef.searchByStatusRequest inValue = new RecruitmentAppClient.RecAppServiceRef.searchByStatusRequest();
            inValue.status = status;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).searchByStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RecruitmentAppClient.RecAppServiceRef.addApplicationResponse RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.addApplication(RecruitmentAppClient.RecAppServiceRef.addApplicationRequest request) {
            return base.Channel.addApplication(request);
        }
        
        public bool addApplication(RecruitmentAppClient.RecAppServiceRef.application application) {
            RecruitmentAppClient.RecAppServiceRef.addApplicationRequest inValue = new RecruitmentAppClient.RecAppServiceRef.addApplicationRequest();
            inValue.application = application;
            RecruitmentAppClient.RecAppServiceRef.addApplicationResponse retVal = ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).addApplication(inValue);
            return retVal.added;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.addApplicationResponse> RecruitmentAppClient.RecAppServiceRef.ApplicationsManager.addApplicationAsync(RecruitmentAppClient.RecAppServiceRef.addApplicationRequest request) {
            return base.Channel.addApplicationAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecruitmentAppClient.RecAppServiceRef.addApplicationResponse> addApplicationAsync(RecruitmentAppClient.RecAppServiceRef.application application) {
            RecruitmentAppClient.RecAppServiceRef.addApplicationRequest inValue = new RecruitmentAppClient.RecAppServiceRef.addApplicationRequest();
            inValue.application = application;
            return ((RecruitmentAppClient.RecAppServiceRef.ApplicationsManager)(this)).addApplicationAsync(inValue);
        }
    }
}
